name: AntiSwerPlugin
version: 1.1.1
author: booby
main: me.booby.antiswerplugin.AntiSwerPlugin

commands:
  swer:
    aliases: ["antiswer", "superswer", "sausageswer"]
  swerreload:
    aliases: ["antiswerreload", "superswerreload", "sausageswerreload"]
