name: AntiSwerPlugin
version: 1.3
author: booby
main: me.booby.antiswerplugin.AntiSwerPlugin

commands:
  swer:
    aliases:
      - "antiswer"
      - "superswer"
      - "sausageswer"
  swerreload:
    aliases:
      - "antiswerreload"
      - "superswerreload"
      - "sausageswerreload"
    permission: "antiswer.reload"
